In [2]:
from mydatabinary import *
import cv2
from pathlib import Path
# img = cv2.imread('D:\diabs\Bacteroides.fragilis\masked\Bacteroides.fragilis_0003_gt.tif')[0:512,0:512,:]
# img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
# i=np.stack((img,img,img,img))
# print(img.shape)
# print(np.unique((img).reshape((-1,3)),axis =0))
# np.unique(one_hot(img).reshape((-1,34)),axis =0)

[[192, 192, 192], [0, 0, 255], [0, 0, 128], [0, 255, 0], [0, 255, 255], [0, 255, 128], [0, 128, 0], [0, 128, 255], [0, 128, 128], [255, 0, 0], [255, 0, 255], [255, 0, 128], [255, 255, 0], [255, 128, 0], [255, 128, 255], [255, 128, 128], [128, 0, 0], [128, 0, 255], [128, 0, 128], [128, 255, 0], [128, 255, 255], [128, 255, 128], [128, 128, 0], [128, 128, 255], [128, 128, 128], [64, 64, 64], [64, 64, 191], [64, 191, 64], [64, 191, 191], [191, 64, 64], [191, 64, 191], [191, 191, 64], [0, 0, 0], [255, 255, 255]]
34


In [3]:
def dataGenerator1(path1,seed=1):
    size = 512
    image_datagen = ImageDataGenerator()
    image_generator = image_datagen.flow_from_directory(
        path1,
        target_size=(size, size),
        classes = ["images"],
        class_mode = None,
        batch_size = 4,
        save_to_dir='check/images',
        save_prefix='images',
        seed = seed)
    mask_generator = image_datagen.flow_from_directory(
        path1,
        target_size=(size, size),
        classes = ["masks"],
        class_mode = None,
        batch_size = 4,
        save_to_dir='check/mask',
        save_prefix='mask',

        seed = seed)
    data_generator = zip(image_generator, mask_generator)
    for (image, mask) in data_generator:
        image, mask = adjustData(image,mask)
        train = (image, mask)
        #print(train[0].shape)
        yield train
path = os.path.dirname(os.getcwd())
path = Path(path)
magnification = "100x"

val_name = path/"data/validationcr"
train_name = path/"data/traincr"
train_name = path/"data/traincr"

In [25]:

# train = dataGenerator1(train_name)
import numpy as np
arr2=np.ones((4,3))
arr3=np.array([1,2,3])
print(np.multiply(arr2,arr3))
arr2*arr3
np.dot(arr2,arr3)


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


array([6., 6., 6., 6.])

In [5]:
for i in train:
    print(i[0].shape)

Found 8300 images belonging to 1 classes.
Found 8300 images belonging to 1 classes.
(4, 512, 512, 3)
(4, 512, 512, 3)
(4, 512, 512, 3)
(4, 512, 512, 3)


KeyboardInterrupt: 